## anamoly detection
- here we will detect the anomaly scenario
- for example: the model will see "This 52,000 education payment is suspicious — 
average education spend is 8,000"

- we have two approaches for this, we will implement both and use the best one

- approach 1 — Statistical (Z-Score)
Flag any transaction where amount is more than 2 standard deviations above the category mean. Simple, explainable, fast.
- approach 2 — Isolation Forest
A proper ML algorithm designed specifically for anomaly detection. More sophisticated, handles complex patterns.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler
import joblib

In [3]:
df = pd.read_excel("../data/sample_transactions.xlsx")
df.head()

  transaction_id        date day_of_week  ...   city is_weekend is_anomaly
0       TXN00001  2024-01-02     Tuesday  ...  Delhi      False       True
1       TXN00002  2024-01-02     Tuesday  ...  Delhi      False      False
2       TXN00003  2024-01-02     Tuesday  ...  Delhi      False      False
3       TXN00004  2024-01-02     Tuesday  ...  Delhi      False      False
4       TXN00005  2024-01-02     Tuesday  ...  Delhi      False      False

[5 rows x 14 columns]

In [4]:
## converting date
df['date'] = pd.to_datetime(df['date'])
print(df['date'].dtype)

datetime64[us]

In [5]:
## cleaning description text
df['description']= df['description'].str.lower().str.strip()

### Approach 1: Z-score

- for each category we will find 'mean' and 'standard deviation'
- the for each transaction z score is computed
   - z-score = (amount - mean)/std
   - if z-score > 2, then we flag it as an anomaly

In [6]:
## implementing approach 1

category_stats = df.groupby('category')['amount'].agg(['mean','std']).reset_index()
category_stats.columns=['category', 'mean_amount', 'std_amount']
print(category_stats)

         category   mean_amount    std_amount
0           Bills   2467.164545   2200.135946
1       Education  17838.963617  16194.819708
2   Entertainment   1499.183960   1145.203114
3         Fitness   4735.143750   4147.539363
4            Food    927.652878   1560.256312
5            Fuel   1985.153934   1495.235392
6       Groceries   2733.426923   2556.733620
7      Healthcare   4227.100656   2385.475138
8       Insurance   8204.649118   4917.545191
9     Investments  15573.175082   8982.825886
10  Personal Care   2853.718000   1675.515805
11           Rent  15474.642533   5877.428922
12       Shopping   5871.068387   5463.501740
13         Travel   2912.124257   3623.276553
14      Utilities   3533.739595   2624.102296

In [7]:
## merging back into the maine dataframe

df = df.merge(category_stats, on='category')

# on decides based on which column both the dataframes are being merged

df.head()

  transaction_id       date day_of_week  ... is_anomaly   mean_amount   std_amount
0       TXN00001 2024-01-02     Tuesday  ...       True    927.652878  1560.256312
1       TXN00002 2024-01-02     Tuesday  ...      False    927.652878  1560.256312
2       TXN00003 2024-01-02     Tuesday  ...      False   3533.739595  2624.102296
3       TXN00004 2024-01-02     Tuesday  ...      False  15474.642533  5877.428922
4       TXN00005 2024-01-02     Tuesday  ...      False  15474.642533  5877.428922

[5 rows x 16 columns]

In [8]:
## computing the z_score
df['z_score'] = (df['amount']-df['mean_amount']) / df['std_amount']

In [27]:
# flag anamonaly column
df['anomaly_zscore'] = df['z_score']>2.0

df.head()

  transaction_id       date  ... category_encoded anomaly_iforest
0       TXN00001 2024-01-02  ...                4           False
1       TXN00002 2024-01-02  ...                4           False
2       TXN00003 2024-01-02  ...               14           False
3       TXN00004 2024-01-02  ...               11           False
4       TXN00005 2024-01-02  ...               11           False

[5 rows x 20 columns]

In [28]:
## now we check how many rows got anomaly detection
print("number of actual anomalies in data: ", df['is_anomaly'].sum())
print("Anomalies detected: ",df['anomaly_zscore'].sum())

print(df[df['anomaly_zscore']==True][['description', 'category', 'amount', 'z_score']])

number of actual anomalies in data:  55
Anomalies detected:  38
                 description       category    amount   z_score
0               pos txn 9289           Food   8123.00  4.611644
14                 zmto*6301           Food  11294.10  6.644067
29    online course purchase      Education  81218.00  3.913538
39           monthly grocery      Groceries  18348.40  6.107391
60                   bb*6315      Groceries  17383.40  5.729957
69       beauty subscription  Personal Care   9321.12  3.859947
118         account transfer    Investments  41858.88  2.926218
130            wellness plan        Fitness  14288.24  2.303317
151          bigbasket order      Groceries  11619.40  3.475518
302     subscription renewal      Utilities  18632.60  5.753915
318               nykaa*7445       Shopping  37475.15  5.784583
322         late night order           Food   6448.60  3.538487
331             neft payment         Travel  30550.52  7.628012
395     auto debit insurance      Insurance  24400.20  3.293422
404         blinkit delivery      Groceries  10907.80  3.197194
492          utility payment          Bills  11590.40  4.146669
507           membership fee      Education  85442.12  4.174369
510               dining out           Food   5929.90  3.206042
513             myntra order       Shopping  37926.10  5.867122
643                gplay sub  Entertainment   6605.84  4.459171
645          telecom payment          Bills  15279.24  5.823311
654         flat maintenance      Utilities   9962.48  2.449882
657         rickshaw payment         Travel  19051.62  4.454392
681                auto ride         Travel  11445.14  2.355055
757             dinner order           Food  10077.60  5.864387
801               ott bundle  Entertainment   8330.40  5.965069
819            movie tickets  Entertainment   3939.08  2.130536
891      cult.fit membership        Fitness  16758.44  2.898899
893             app purchase           Food  11752.30  6.937736
1009              dining out           Food   9903.70  5.752931
1050              nykaa*7473       Shopping  41284.00  6.481728
1131          dunzo delivery           Food   9153.80  5.272305
1171               hp petrol           Fuel   9371.36  4.939828
1235         bigbasket order      Groceries  18023.00  5.980120
1255        electricity bill          Bills   8371.64  2.683687
1287        late night order           Food   8904.60  5.112588
1319       scheduled payment          Bills   7786.76  2.417849
1393    subscription renewal        Fitness  20716.16  3.853132

## Approach 2: isolation forest
it looks at the entire dataset and finds points that are easisest to isolate from the rest

- two features will be given as input: amount and category (in encoded form)

In [29]:
from sklearn.preprocessing import StandardScaler

#encoding category as numbers
df['category_encoded'] = df['category'].astype('category').cat.codes

# prepareing the features
features = df[['amount', 'category_encoded']]
scaler = StandardScaler()
features_scaled = scaler.fit_transform(features)

In [30]:
# training isolation forest

iso_forest = IsolationForest(contamination=0.04, random_state=42)
df['anomaly_iforest'] = iso_forest.fit_predict(features_scaled)

# we need iso forest to return -1 for anomaly and 1 for normal

df['anomaly_iforest'] = df['anomaly_iforest'] == -1

##checking the total number of anomalies detected
print('anomalies detected by isolation forest',df['anomaly_iforest'].sum())

df.head(2)

anomalies detected by isolation forest 56

  transaction_id       date  ... category_encoded anomaly_iforest
0       TXN00001 2024-01-02  ...                4           False
1       TXN00002 2024-01-02  ...                4           False

[2 rows x 20 columns]

In [31]:
## checking the classification report of both z score and isolation forest

from sklearn.metrics import classification_report, accuracy_score

## for z score
print("z-score")
print(accuracy_score(df["is_anomaly"], df['anomaly_zscore']))
print(classification_report(df["is_anomaly"], df['anomaly_zscore']))

## for isolation forest
print("isolation forest")
print(accuracy_score(df["is_anomaly"], df['anomaly_iforest']))
print(classification_report(df["is_anomaly"], df['anomaly_iforest']))

z-score
0.9878397711015737
              precision    recall  f1-score   support

       False       0.99      1.00      0.99      1343
        True       1.00      0.69      0.82        55

    accuracy                           0.99      1398
   macro avg       0.99      0.85      0.91      1398
weighted avg       0.99      0.99      0.99      1398

isolation forest
0.9506437768240343
              precision    recall  f1-score   support

       False       0.97      0.97      0.97      1343
        True       0.38      0.38      0.38        55

    accuracy                           0.95      1398
   macro avg       0.67      0.68      0.68      1398
weighted avg       0.95      0.95      0.95      1398

Z-Score worked better than Isolation Forest because it sets thresholds within each category, which makes more sense when spending habits differ a lot across categories

- Z-Score: Precision 1.0, Recall 0.69, F1 0.82
- Isolation Forest: Precision 0.38, Recall 0.38, F1 0.38

In [32]:
# we wil be using z score with threhold value of 2.0
ANOMALY_THRESHOLD = 2.0

In [33]:
## we do not need a trained model file to be saved for Z-score
#we will just save the anomaly threshold we are using
## and the columns used in computing z scorw which are saved in category_stats

joblib.dump(ANOMALY_THRESHOLD, '../models/anomaly_threshold.pkl')
print("Anomaaly threshold saved")

joblib.dump(category_stats,'../models/anomaly_category_stats.pkl')
print("category stats saved")

Anomaaly threshold saved
category stats saved